name: blogstore
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.4

resolution: workspace

dependencies:
  core: any
  firebase_analytics: any
  firebase_auth: any
  firebase_core: any
  firebase_crashlytics: any
  firebase_messaging: any
  flutter:
    sdk: flutter
  kaisel: any
  l10n: any

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
