name: core
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.13.4

resolution: workspace

# Add regular dependencies here.
dependencies:
  blogstore_client:
    path: ../../../blogstore_client
  dio: ^5.11.1
  drift: any
  drift_flutter: ^0.3.1
  firebase_messaging: any # comment me
  flutter:
    sdk: flutter
  path_provider: ^2.1.6
dev_dependencies:
  build_runner: ^2.16.1
  drift_dev: ^2.35.0
  lints: ^6.0.0
  test: ^1.25.6
