name: _
publish_to: none
# repository: https://github.com/Antinna/workspace

environment:
  sdk: ^3.13.4

workspace:
  - apps/**
  - packages/**


dependencies:
  path: any

dev_dependencies:
  very_good_analysis: ^11.0.0
#  custom_lint_builder: any
